name: Test LaTeX to MkDocs CI/CD

# 1. 触发条件：main 触发
on:
  push:
    branches: [ main ]
    workflow_dispatch:
    repository_dispatch:
      types: [ source_book_updated ]

permissions:
  contents: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 拉取仓库代码
        uses: actions/checkout@v4

      - name: 📥 拉取私有仓库 CCBook 的源码
        uses: actions/checkout@v4
        with:
          repository: 'HNU-CloudComputing/CCBook'
          token: ${{ secrets.NOTIFY_PAT }}
          path: 'latex_source'

      - name: ⚙️ 安装 Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: 🐍 配置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 安装 MkDocs 及主题
        run: |
          pip install mkdocs-material
          pip install pymdown-extensions

      - name: 🔄 运行 Pandoc 转换 (LaTeX -> Markdown)
        run: |
          mkdir -p docs
          cp -r latex_source/figures docs/figures

          cd latex_source
          for file in section/*.tex; do
            [ -e "$file" ] || continue 
            
            filename=$(basename -- "$file")
            filename="${filename%.*}"
            if [[ "$filename" != *"bak"* ]]; then
              pandoc "$file" -f latex -t markdown-multiline_tables-grid_tables-simple_tables -o "../docs/${filename}.md" --wrap=none
            fi
          done
          
          for file in appendix/*.tex; do
            [ -e "$file" ] || continue
            
            filename=$(basename -- "$file")
            filename="${filename%.*}"
            pandoc "$file" -f latex -t markdown-multiline_tables-grid_tables-simple_tables -o "../docs/${filename}.md" --wrap=none
          done

      - name: 🧹 运行全能 Markdown 处理器
        run: python scripts/process_docs.py


      - name: 🚀 构建并自动推送到 gh-pages 分支
        run: mkdocs gh-deploy --force